name: dynamo_annotation
version: 4.6.1-dev
description: >-
  Classes and helper functions that support DYnamoDB JSON code generation via the
  `dynamo_serializable` package.
repository: https://github.com/giocirque/pub-dev/dynamo_json/tree/master/dynamo_annotation
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.4.0
  json_annotation: any

dev_dependencies:
  lints: ^2.0.0
  json_serializable: any
# When changing JsonSerializable class.
#  build_runner: ^2.0.0
#  json_serializable: any
