name: dynamo_annotation
version: 4.6.1-dev
description: >-
  Classes and helper functions that support DYnamoDB JSON code generation via the
  `dynamo_serializable` package.
repository: https://github.com/giocirque/pub-dev/dynamo_json/tree/master/dynamo_annotation
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  json_annotation: ^4.7.0
  meta: ^1.4.0

dev_dependencies:
  json_serializable: ^6.4.1
  lints: ^2.0.0
# When changing DynamoSerializable class.
#  build_runner: ^2.0.0
#  dynamo_serializable: any
