name: dynamo_json
version: 6.3.1
description: >-
  Automatically generate code for converting to and from DynamoDb JSON by annotating
  Dart classes.
repository: https://github.com/giocirque/pub-dev/dynamo_json
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: '^4.7.0'
  async: ^2.9.0
  build: ^2.3.0
  build_config: '^1.1.0'
  collection: ^1.16.0
  meta: ^1.8.0
  path: ^1.8.2
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.1
  source_gen: ^1.2.2
  source_helper: ^1.3.2

dev_dependencies:
  build_runner: ^2.2.0
  build_verify: ^3.0.0
  dart_style: ^2.2.3
  logging: ^1.0.2
  source_gen_test: ^1.0.3
  test: ^1.21.5
  test_descriptor: ^2.0.0
  test_process: ^2.0.2
  yaml: ^3.1.1
