name: example
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dynamo_json:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  path: ^1.8.0
  test: ^1.16.0
