name: cobertura
description: Converts LCOV to Cobertura format; the ideal format for GitHub and Azure DevOps.
version: 1.0.3
homepage: https://pub-dev.dicatania.me/cobertura/
repository: https://github.com/VannaDi/pub-dev
issue_tracker: https://github.com/VannaDi/pub-dev/issues

environment:
  sdk: '>=3.1.2 <4.0.0'

executables:
  cobertura:

dependencies:
  xml: ^6.4.2
  path: ^1.8.3
  args: ^2.4.2
  yaml: ^3.1.2
  tint: ^2.0.1
  meta: ^1.11.0
  cli_badges: ^0.0.2
  collection: ^1.18.0

dev_dependencies:
  test: ^1.24.9
  lints: ^3.0.0
