name: cobertura
description: Converts LCOV to Cobertura format; the ideal format for GitHub and Azure DevOps.
version: 1.0.0
homepage: https://pub-dev.dicatania.me/cobertura/
repository: https://github.com/GioCirque/pub-dev
issue_tracker: https://github.com/GioCirque/pub-dev/issues

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  xml: ^5.3.1
  path: ^1.8.1
  args: ^2.3.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.0
  lints: ^1.0.0
