name: geography
description: A library of geographical entities, their metadata, and relationships. Provides a basic, and an earth, library with methods for finding the nearest entity and measuring distances.
version: 2.0.0
homepage: https://pub-dev.dicatania.me/geography/
repository: https://github.com/VannaDi/pub-dev
issue_tracker: https://github.com/VannaDi/pub-dev/issues

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ">=0.13.1 <2.0.0"
  meta: ^1.0.0
  path: ^1.0.0
  archive: ^3.0.0
  latlong2: ^0.7.0
  diacritic: ^0.1.0
  equatable: ^2.0.0
  collection: ^1.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  uuid: ^4.2.1
  test: ^1.24.9
  lints: ^3.0.0
  coverage: ^1.7.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
