name: geography
description: A library of geography and its metadata.
version: 1.0.0
homepage: https://pub-dev.dicatania.me/geography/
repository: https://github.com/GioCirque/pub-dev
issue_tracker: https://github.com/GioCirque/pub-dev/issues

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  meta: ^1.7.0
  http: ^0.13.4
  path: ^1.8.1
  archive: ^3.1.7
  latlong2: ^0.8.1
  diacritic: ^0.1.3
  equatable: ^2.0.3
  collection: ^1.15.0
  json_annotation: ^4.4.0

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
  coverage: ^1.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
