name: geography
description: A library of geography and its metadata.
version: 1.0.0
homepage: https://dart.dicatania.me
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  meta: ^1.7.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0

dev_dependencies:
  test: ^1.20.1
  http: ^0.13.4
  lints: ^1.0.1
  archive: ^3.1.7
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
