name: geography
description: A library of geographical entities, their metadata, and relationships. Provides a basic, and an earth, library with methods for finding the nearest entity and measuring distances.
version: 1.1.3
homepage: https://pub-dev.dicatania.me/geography/
repository: https://github.com/GioCirque/pub-dev
issue_tracker: https://github.com/GioCirque/pub-dev/issues

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  meta: ^1.7.0
  http: ^0.13.4
  path: ^1.8.0
  archive: ^3.3.0
  latlong2: ^0.8.1
  diacritic: ^0.1.3
  equatable: ^2.0.3
  collection: ^1.16.0
  json_annotation: ^4.4.0

dev_dependencies:
  uuid: ^3.0.6
  test: ^1.21.1
  lints: ^1.0.1
  coverage: ^1.2.0
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
