name: geography
description: A library of geographical entities, their metadata, and relationships. Provides a basic, and an earth, library with methods for finding the nearest entity and measuring distances.
version: 1.1.5
homepage: https://pub-dev.dicatania.me/geography/
repository: https://github.com/VannaDi/pub-dev
issue_tracker: https://github.com/VannaDi/pub-dev/issues

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.1.0
  meta: ^1.10.0
  path: ^1.8.3
  archive: ^3.4.0
  latlong2: ^0.9.0
  diacritic: ^0.1.4
  equatable: ^2.0.5
  collection: ^1.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  uuid: ^4.0.0
  test: ^1.24.6
  lints: ^2.1.1
  coverage: ^1.6.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
