name: dynamo_json
description: A code generator for DynamoDB JSON (de)serialization.
version: 0.0.1
homepage: https://pub-dev.dicatania.me/dynamo_json/
repository: https://github.com/GioCirque/pub-dev
issue_tracker: https://github.com/GioCirque/pub-dev/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.1.0
  build: ^2.3.1
  build_config: ^1.1.1
  collection: ^1.17.0
  equatable: ^2.0.5
  meta: ^1.8.0
  path: ^1.8.2
  source_gen: ^1.2.6
  source_helper: ^1.3.3
  source_span: ^1.9.1

dev_dependencies:
  build_runner: ^2.3.2
  coverage: ^1.6.1
  lints: ^2.0.1
  source_gen_test: ^1.0.4
  test: ^1.21.6
  uuid: ^3.0.6
