name: dynamo_json
description: A Dart `build_runner` to generate `toDynamoJson` and `fromDynamoJson` support methods, similar to `json_serializable`, specifically supporting the `DynamoDB` attribute values.`
version: 0.0.2
homepage: https://pub-dev.dicatania.me/dynamo_json/
repository: https://github.com/VannaDii/pub-dev
issue_tracker: https://github.com/VannaDii/pub-dev/issues

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  analyzer: ^6.3.0
  build: ^2.4.1
  build_config: ^1.1.1
  collection: ^1.18.0
  equatable: ^2.0.5
  meta: ^1.11.0
  path: ^1.8.3
  source_gen: ^1.4.0
  source_helper: ^1.3.4
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.7.1
  lints: ^3.0.0
  source_gen_test: ^1.0.6
  test: ^1.24.9
  uuid: ^4.2.1
