name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.3

      - name: Install Dependencies
        working-directory: geography
        run: make deps

      - name: Ru Tests
        working-directory: geography
        run: make test

      - name: Build Geography
        working-directory: geography
        run: make all

      - name: Document Geography
        working-directory: geography
        run: make docs
