name: 🎯 Build & Pub

on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  # JOB to run change detection
  changes:
    name: 🕵️ Detect Changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      geography: ${{ steps.filter.outputs.geography }}
      cobertura: ${{ steps.filter.outputs.cobertura }}
      dfat: ${{ steps.filter.outputs.dfat }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            geography:
              - 'geography/**'
            cobertura:
              - 'cobertura/**'
            dfat:
              - 'dfat/**'

  geography:
    name: 🌍 Geography
    needs: changes
    if: ${{ needs.changes.outputs.geography == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: 👷 Build Geography
        working-directory: geography
        run: make all

      - name: 🚀 Publish geography
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
          package_path: geography

  cobertura:
    name: ⛱ Cobertura
    needs: changes
    if: ${{ needs.changes.outputs.cobertura == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: 👷 Build Cobertura
        working-directory: cobertura
        run: make all

      - name: 🚀 Publish cobertura
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
          package_path: cobertura

  dfat:
    name: 🤖 dfat
    needs: changes
    if: ${{ needs.changes.outputs.dfat == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: 👷 Build dfat
        working-directory: dfat
        run: make all

      - name: 🚀 Publish dfat
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
          package_path: dfat
