name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  geography:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: Build Geography
        working-directory: geography
        run: make all

      - name: Document Geography
        working-directory: geography
        run: make docs

  cobertura:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: Build Cobertura
        working-directory: cobertura
        run: make all

      - name: Document Cobertura
        working-directory: cobertura
        run: make docs
