name: deploy

on:
  push:
    tags:
      - "v*"

jobs:
  geography:
    name: 🌍 Geography
    if: ${{ github.ref_type == 'tag' && endsWith(github.ref_name, '-geography') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: 🚀 Publish geography
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
          package_path: geography

  cobertura:
    name: ⛱ Cobertura
    if: ${{ github.ref_type == 'tag' && endsWith(github.ref_name, '-cobertura') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: 🚀 Publish cobertura
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
          package_path: cobertura
