name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # JOB to run change detection
  changes:
    name: 🕵️ Detect Changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      geography: ${{ steps.filter.outputs.geography }}
      cobertura: ${{ steps.filter.outputs.cobertura }}
      dynamo_json: ${{ steps.filter.outputs.dynamo_json }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: "none"
          filters: .github/build_path_filters.yaml

  geography:
    name: 🌍 Geography
    needs: changes
    if: ${{ needs.changes.outputs.geography == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: 👷 Build Geography
        working-directory: geography
        run: make all

  cobertura:
    name: ⛱ Cobertura
    needs: changes
    if: ${{ needs.changes.outputs.cobertura == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: 👷 Build Cobertura
        working-directory: cobertura
        run: make all

  dynamo_json:
    name: 📇 DynamoJson
    needs: changes
    if: ${{ needs.changes.outputs.dynamo_json == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: 👷 Build dynamo_json
        working-directory: dynamo_json
        run: make all
